version: "3.9"
services:
  graph-explorer:
    image: graph-explorer:latest
    ports:
      - "5173:5173"
      - "8182:8182"
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}